### ISSUE TITLE
why isn't the latest version on hackage?

### ISSUE THREAD

**Issue by ublubu** [ccll/hs-sdl2-image#5]
hackage only has 0.1.1.0, which still has that "missing C library: sdl2" problem on linux. Not critical, but kinda annoying.

**Comment by mtolly** [comment]
:+1: The version on Hackage doesn't have #4, so it rejects the current `sdl2` without `--allow-newer=sdl2`. An update would be appreciated!

**Comment by ccll** [comment]
Done!
I've added a changelog file and uploaded the latest version as "v0.1.3.1".
Thanks for the report.
